name: Deploy MkDocs to GitHub Pages
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        pip install mkdocs
        pip install mkdocs-material
        pip install mkdocs-heti-plugin
        pip install mkdocs-git-revision-date-localized-plugin
        pip install mkdocs-changelog-plugin
    - name: Build the MkDocs site
      run: mkdocs build
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: ./site
        force: true
